# illa-builder 

version: "3.9"

networks:
  frontend-tier:
  backend-tier:

services:
  illa-frontend:
    container_name: illa-frontend
    restart: always
    image: "illasoft/illa-frontend:latest"
    environment:
    - API_SERVER_ADDRESS=localhost
    - API_SERVER_PORT=9999
    - RELEASE_VERSION=TESTONLY
    networks:
      - frontend-tier
    ports:
      - "80:80"
  illa-backend:
    container_name: illa-backend
    restart: always
    image: "illasoft/illa-backend:latest"
    environment:
      - GIN_MODE=release
      - ILLA_PG_ADDR=illa-database
      - WEBSOCKET_SERVER_ADDRESS=localhost
      - WEBSOCKER_PORT=8000
      - ILLA_DEPLOY_MODE='self-host'
    networks:
      - frontend-tier
      - backend-tier
    ports:
      - "9999:9999"
    depends_on:
      - illa-database
  illa-backend-ws:
    container_name: illa-backend-ws
    restart: always
    image: "illasoft/illa-backend-ws:latest"
    environment:
      - ILLA_PG_ADDR=illa-database
      - WEBSOCKET_SERVER_ADDRESS=localhost
      - WEBSOCKER_PORT=8000
    networks:
      - frontend-tier
      - backend-tier
    ports:
      - "8000:8000"
    depends_on:
      - illa-database
  illa-database:
    container_name: illa-database
    restart: always
    image: "illasoft/illa-database:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend-tier
    ports:
      - "5432:5432"
    volumes: 
      - /var/lib/illa/database/postgresql:/var/lib/postgresql/data

